a=int(input("Enter the a value: "))
b=int(input("Enter the b value: "))
print("Addition  value is: ",a+b)
print("Subtraction value is: ",a-b)
print("Multiplication value is: ",a*b)
print("Division value is: ",a/b)
print("Remainder value is: ",a%b)
print("Exponential value is: ",a**b)
print("Floor division value is: ",a//b)
